Sprint_5
Hachukov/Quiz-ios-YP pull request #3
Opened 2022-10-22 11:48 UTC by Hachukov

Привет добавил в проект JSON файл так как предположил что мы его будем использовать на спринте 6

2022-10-22 12:30 UTC, ABashkirova requested changes
Давайте поправим следующие замечания, также проверим внимательно макеты

2022-10-22 12:30 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    var delegate: AlertPresenterProtocol?
Здесь указана сильная ссылка на вью контроллер (через протокол), такие ссылки приводят к retain cycle

2022-10-22 12:30 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +            self.delegate?.updateGameCounter()
Обращаясь к self не забывайте слабый список захвата

2022-10-22 12:30 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
а почему этот код внутри viewController? 

задачей этого спринта стояло разделить ответственность кода, а работа по генерации вопросов должна быть вынесена в отдельную сущность (QuestionFactory)

Также, здесь используется грубый и не безопасный код, привыкайте использовать операторы и условные конструкции для разыменовывания опционалов

2022-10-22 12:30 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    func updateGameCounter() {
нейминг скорее про resetGame :)

2022-10-22 12:30 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.questionFactory?.requestNextQuestion()
self можно опустить

2022-10-22 12:30 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        present(delegate.showAlert(alertModel: alertModel), animated: true)
так формально ок, хотя выглядит немного странно и не читаемо, предлагаю другой вариант
```suggestion
        guard let alert = delegate?.showAlert(alertModel: alertModel) else { return }
        present(alert, animated: true)
```

но судя по названию метода showAlert, тут логическая ошибка в декомпозии/ нейминге

контроллер держит презентер(delegate), и он умеет показывать алерт (showAlert), то есть предполагается, что презентер способен вызвать метод present. Делается либо через дополнительный параметр в функции, либо через явную ссылку в презентере на UIViewController

2022-10-22 12:30 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction func noButton(_ sender: Any) {
модификаторы приватности пропущены, проверьте весь код на это

2022-10-22 12:30 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    weak var delegate: QuestionFactoryDelegate?
👍

2022-10-22 12:30 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +            bestGame.date = Date()
не совсем корректно сохранять только correct и date, по идее у вас это будет работать, потому что количество вопросов не меняется, но такое решение будет работать до тех пор пока вы не меняете их количество :) 
Лучше создать новый объект и сохранить его 

if bestGame < currentGame  { bestGame = currentGame)

2022-10-22 12:30 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +            guard let data = userDefaults.data(forKey: Keys.totalAccuracy.rawValue),
у **userDefaults** есть также методы для примитивов и лучше использовать их integer/double/bool

2022-10-22 12:30 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
В целом вы можете оставить этот способ получения фильмов из json, но тогда надо написать и часть использования его. 

В данном случае код написан, и не используется. Такой код называется мертвым и его следует удалять перед сдачей

2022-10-22 12:30 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
перенос строки внутри строки созданной таким образом и считается за `\n`, дополнительно его ставить не надо. Проверьте по макету, что текст совпадает
<img width="543" alt="Screenshot 2022-10-22 at 16 18 43" src="https://user-images.githubusercontent.com/20269264/197338835-15487479-8ae2-45b6-a17c-a89a7796faa1.png">

2022-10-26 05:11 UTC, ABashkirova requested changes

2022-10-26 05:11 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +            self.delegate?.resetGame()
```suggestion
                                   style: .cancel) { [weak self] _ in
            guard let self = self else { return }
            self.delegate?.resetGame()
```

2022-10-26 05:11 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +            self.delegate?.resetGame()
После фигурной скобки принято ставить пробел / или перенос. В этих случаях пробел уместнее

2022-10-26 05:11 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +        totalAccuracy = Double(count) / Double(amount) * 100
Формула не учитывает предыдущие игры

2022-10-27 18:28 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +                return 0
Стало хуже. вариант с примитивом был правильным

2022-11-03 20:58 UTC, ABashkirova commented
Работу можно смерджить

2022-11-07 12:37 UTC, closed without merging

2022-11-07 12:37 UTC, Hachukov commented
not need yet