Sprint 6
Hachukov/Quiz-ios-YP pull request #4
Opened 2022-11-03 18:52 UTC by Hachukov

Sprint 6

2022-11-03 21:08 UTC, ABashkirova requested changes

2022-11-03 21:08 UTC, ABashkirova commented on MovieQuiz/Models/MostPopularMovies.swift
> +//}
Лишнее удалим?

2022-11-03 21:08 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    weak var alertPresenterDelegat: AlertPresenterDelegate?
```suggestion
    weak var alertPresenterDelegate: AlertPresenterDelegate?
```

2022-11-03 21:08 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Failed to load image")
Сделаете?)

2022-11-03 21:08 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +            let correctAnswer = rating > 7
Кажется текст вопроса будет содержать цифру отличную от 7. Тогда вы делаете логическую ошибку в вычислении корректности вопроса.

2022-11-03 21:08 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    weak var alertPresenterProtocol: AlertPresenterProtocol?
Переменная не используется здесь, тогда зачем она?

2022-11-03 21:08 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    weak var alertPresenterDelegat: AlertPresenterDelegate?
тоже не используется, тогда зачем?

2022-11-07 13:18 UTC, Hachukov commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Failed to load image")
Да ))

2022-11-08 14:57 UTC, Hachukov commented on MovieQuiz/Services/QuestionFactory.swift
> -                print("Failed to load image")
Вызываю тут алерт  и когда выключаю сеть он срабатывает, но по нажатию на кнопку повторить то  функция resetGame() не срабатывает как мне нужно , в итоге получается что вызываю метод из которого я вызвал алерт

2022-11-08 19:26 UTC, ABashkirova requested changes

2022-11-08 19:26 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
>               // TODO: - сделать алерт для ошибки
Done!
```suggestion
```

2022-11-08 19:26 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                    self?.delegate?.didFailToLoadData(with: error)
тут замечу, что функция все равно продолжит выполнение и дойдет до вызова didRecieveNextQuestion

2022-11-08 19:26 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.questionText = "Рейтинг этого фильма больше чем \(String(format: "%.1f", rating + Float.random(in: 0.2...(10.0 - rating)))) ?"
`0.2...(10.0 - rating)` боюсь, что такой код может завершиться падением в рантайме с такой ошибкой
`Fatal error: Range requires lowerBound <= upperBound`, когда рейтинг будет в диапазоне от (9.8,10] 

Из-за этой ошибки, я не смогу принять работу

2022-11-08 19:26 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.questionText = "Рейтинг этого фильма больше чем \(String(format: "%.1f", rating + Float.random(in: 0.2...(10.0 - rating)))) ?"
Предлагаю убрать всю логику формирования вопроса к исходному виду и начать придумывать алгоритм с нуля, сейчас здесь и без того сложный код получился :)

2022-11-08 20:38 UTC, ABashkirova commented
@Hachukov запустить же и проверить тоже надо:
![Uploading Screenshot 2022-11-09 at 00.37.08.png…]()

2022-11-10 12:36 UTC, ABashkirova approved these changes

2022-11-10 12:36 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Failed to load image")
Очень жалко, что убрали проверку, почему?

2022-11-17 19:41 UTC, closed without merging